version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  adminer:
    container_name: admin-panel
    image: adminer
    restart: always
    ports:
      - 5000:8080

  api:
    container_name: api
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: pnpm migrate-and-dev
    depends_on:
      - db
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env